image: maven:3-jdk-8

stages:
  - build
#  - run

before_script:
  - echo "Start CI/CD"

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

#run:
#  image: maven:3-jdk-8
#  stage: run
#  script: "mvn spring-boot:run"
#  only:
#    - master


after_script:
  - echo "End CI/CD"
